### PR TITLE
Rails5

### PR DESCRIPTION
**Pull request by mnoack**
This PR adds rails 5+ compatibility in the first commit and the other commits ensure this project has Travis testing running to ensure that changes continue to work with rails 3, 4, and 5 and multiple ruby versions.

### CODE REVIEW

**Comment by mnoack** [comment]
Bump @flavorjones - Happy to tweak this PR if needed or even be added as a maintainer (or move this repo to our organisation, etc.) if needed.

**Comment by mnoack** [comment]
Bump @flavorjones - Again, happy to tweak this PR if needed or even be added as a maintainer (or move this repo to our organisation, etc.) if needed.

**Comment by mnoack** [comment]
Bump @flavorjones - Sorry for being annoying. I'm happy to be added a commiter & gem releaser so I can be annoyed by people making PR's :)

**Comment by flavorjones** [comment]
Sorry! Been taking a break from OSS. Will take a look in the next two days.
Also happy to have help ... Let's talk offline.

**Comment by mnoack** [comment]
Bump @flavorjones :)

**Comment by arcreative** [comment]
@flavorjones This is a really trivial PR, can you take a quick look and merge?  Not wanting to deal with figuring out broken dependencies by relying on clones' branches :-)

**Comment by mnoack** [comment]
Also @flavorjones - I'm happy to have people like myself added as maintainers to take to burden off you, we can even move the repo to our company if needed (only if we need admin access to integrate things like travis, etc.)

**Comment by flavorjones** [comment]
Looking into it now.

**Comment by flavorjones** [comment]
Hi,

You haven't followed the patterns set in the `rails_test` directory and added any test coverage for Rails 5. This is probably my fault, because so much of the testing pattern is unobvious and hacky. I'll have to add some tests for this.

This commit also implies ending support for older versions of Rails that are currently supported. I'm OK with that, but would have preferred to discuss first. We'll need to bump the version number to indicate we're dropping support.

For right now, no action on your part needed, but I do want to point out, @arcreative, that "trivial" is a loaded word.

**Comment by flavorjones** [comment]
Released v2.0.0 with Rails 5 support. Thanks for your support.

**Comment by arcreative** [comment]
@flavorjones No offense intended, just trying to underline that the  functional changes comprised of a few lines

**Comment by mnoack** [comment]
Thanks very much @flavorjones - Yes the code change was trivial, but the testing was not

**Pull request closed without merging**
